# Generated by Django 2.2.6 on 2019-10-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191019_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choise_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=' ', max_length=200, verbose_name='choice_text'),
        ),
    ]
